
ERR_BAD_USER_ID = "ERR_BAD_USER_ID"
ERR_BAD_STAN_ID = "ERR_BAD_STAN_ID"
ERR_BAD_PKUPAC_ID = "ERR_BAD_PKUPAC_ID"
ERR_BAD_KUPAC_ID = "ERR_BAD_KUPAC_ID"
ERR_DUPLICATED_USERNAME = 'ERR_DUPLICATED_USERNAME'
ERR_BAD_CREDENTIALS = 'ERR_BAD_CREDENTIALS'
ERR_FORBIDDEN_FOR_ROLE = 'ERR_FORBIDDEN_FOR_ROLE'
ERR_OBJECT_IS_DELETED = 'ERR_OBJECT_IS_DELETED'
ERR_BAD_STATUS = 'ERR_BAD_STATUS'
MISSED_SESS_ID = 'MISSED_SESS_ID'
SESSION_NOT_VALID = 'SESSION_NOT_VALID'
ERR_DUPLICATED_PKUPAC = 'ERR_DUPLICATED_PKUPAC'
