"""initial migration

Revision ID: 197e55772a77
Revises: 
Create Date: 2021-11-01 14:55:20.160797

"""
from alembic import op
import sqlalchemy as sa

from core import data_types


# revision identifiers, used by Alembic.
revision = '197e55772a77'
down_revision = None
branch_labels = None
depends_on = None

ADMINISTRATOR = 'administrator'  # administriraju sistemom
PRODAVAC = 'prodavac'  # osnovne operacije
FINANSIJE = 'finansije'  # osnovne operacije + kreiranje cena, broj ugovora...

USER_ROLES = (
    (ADMINISTRATOR, ADMINISTRATOR),
    (PRODAVAC, PRODAVAC),
    (FINANSIJE, FINANSIJE)
)

KUPAC_TYPES = (
    ('fizicko', 'fizicko'),
    ('pravno', 'pravno')
)

STATUS = (
    ('potencijalni', 'potencijalni'),
    ('rezervisao', 'rezervisao'),
    ('kupio', 'kupio'),
)

OR_TYPES = (
    ('jug', 'jug'),
    ('zapad', 'zapad'),
    ('sever', 'sever'),
    ('istok', 'istok')
)

STATUS_TYPES = (
    ('dostupan', 'dostupan'),
    ('rezervisan', 'rezervisan'),
    ('prodat', 'prodat')
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_kupac',
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('broj_telefona', sa.String(length=20), nullable=False),
    sa.Column('jmbg', sa.String(length=20), nullable=False),
    sa.Column('adresa', sa.Text(), nullable=False),
    sa.Column('tip', data_types.StringChoiceType(choices=KUPAC_TYPES, length=20), server_default='fizicko', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broj_telefona'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('jmbg')
    )
    op.create_table('tbl_user',
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('role', data_types.StringChoiceType(choices=USER_ROLES, length=20), server_default='prodavac', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_stan',
    sa.Column('lamela', sa.String(length=10), nullable=False),
    sa.Column('kvadratura', sa.Float(), nullable=False),
    sa.Column('sprat', sa.Integer(), nullable=False),
    sa.Column('broj_soba', sa.Float(), nullable=False),
    sa.Column('orjentisanost', data_types.StringChoiceType(choices=OR_TYPES, length=20), nullable=False),
    sa.Column('broj_terasa', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.Column('status', data_types.StringChoiceType(choices=STATUS_TYPES, length=20), server_default='dostupan', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_potencijlani_kupac',
    sa.Column('stan_id', sa.Integer(), nullable=False),
    sa.Column('kupac_id', sa.Integer(), nullable=False),
    sa.Column('cena_za_kupca', sa.Float(), nullable=False),
    sa.Column('napomena', sa.Text(), nullable=False),
    sa.Column('broj_ugovora', sa.String(length=30), nullable=False),
    sa.Column('datum_ugovora', sa.DateTime(), nullable=False),
    sa.Column('status', data_types.StringChoiceType(choices=STATUS, length=20), server_default='rezervisao', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['kupac_id'], ['tbl_kupac.id'], ),
    sa.ForeignKeyConstraint(['stan_id'], ['tbl_stan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broj_ugovora')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_potencijlani_kupac')
    op.drop_table('tbl_stan')
    op.drop_table('tbl_user')
    op.drop_table('tbl_kupac')
    # ### end Alembic commands ###
