"""add nacin_kupovine

Revision ID: 31781fb89265
Revises: ab06ae501084
Create Date: 2021-11-16 14:35:00.224979

"""
from alembic import op
import sqlalchemy as sa

from core import data_types


# revision identifiers, used by Alembic.
revision = '31781fb89265'
down_revision = 'ab06ae501084'
branch_labels = None
depends_on = None

NACIN_KUPOVINE = (
    ('kes', 'kes'),
    ('kredit', 'kredit'),
    ('ucesce_i_kredit', 'ucesce_i_kredit')
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_potencijlani_kupac', sa.Column(
        'nacin_kupovine',
        data_types.StringChoiceType(choices=NACIN_KUPOVINE, length=20), nullable=True)
    )
    op.add_column('tbl_stan', sa.Column('adresa', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_stan', 'adresa')
    op.drop_column('tbl_potencijlani_kupac', 'nacin_kupovine')
    # ### end Alembic commands ###
