"""napomena_nullable

Revision ID: ab06ae501084
Revises: d5312c5e3e81
Create Date: 2021-11-03 13:01:11.801769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab06ae501084'
down_revision = 'd5312c5e3e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_potencijlani_kupac', 'napomena',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_potencijlani_kupac', 'napomena',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
